### ISSUE TITLE
MakeGood AU Standard 2/4 Gang switch

### ISSUE THREAD

**Issue by sillyfrog** [sillyfrog/contact#4]
Notes about flashing the MakeGood 4 gang switch with Tasmota:

Use the following template:
```
{"NAME":"MakeGood 4 Gang","GPIO":[0,0,0,0,0,0,0,0,0,0,54,0,0],"FLAG":0,"BASE":54}
```

And once on the network and the template applied, run the following command:
```
Backlog TuyaMCU 11,1; TuyaMCU 12,2; TuyaMCU 13,3; TuyaMCU 14,4; TuyaMCU 33,104; TuyaMCU 31,103; TuyaMCU 32,102;
```

**Comment by andyidau** [comment]
I’ve got 1-, 2-, 3-, and 4-gang versions of this switch, all specify the model number MG-MD04W. Would it be possible to get the instructions for all four variants?

**Comment by sillyfrog** [comment]
@andyidau I have only just got a 2 gang, but it looks like the same template will work, with the following commands:
```
Backlog TuyaMCU 11,1; TuyaMCU 12,2; TuyaMCU 32,102; TuyaMCU 31,103; TuyaMCU 33,104; 
```
(I'll post the template shortly to the site).

Based on this, I'm guessing the 1 and 3 gang will be similar, just by removing the `TuyaMCU` `12`, `13` and `14`, and `14` respectively. (For all my testing, I use by [Bookmarklet](https://github.com/sillyfrog/Tasmota-Tuya-Helper) to simplify the whole process, it allows me to test each DpId quickly, and figure out what does what)

**Comment by networkdetective** [comment]
This template doesn't specify the "Tuya Tx" and "Tuya Rx" GPIOs.

Did you forget?

**Comment by sillyfrog** [comment]
@networkdetective I think it may come from the underlying `Base 54` template (I had a similar thought) - not 100% sure how these tie in together, but I found it's working with the latest Tasmota release (v8.3.1). Are you having issues?

**Comment by dhilbig** [comment]
Hi, received what looks like one of these from another source, although the model number on the back is NO:MG-MD04W. I have not been able to get it to flash at all. Did you have any trouble with this model. I have several of the following types, [https://templates.blakadder.com/RY-RSM104.html](https://templates.blakadder.com/RY-RSM104.html), which internally are very similar, and I was able to flash them easily but took me a while to work out they were MCU. I also think your template may be incorrect and would be more like the RY-RSM104. They both are using the TYWE3S wifi controller. Also found a good reference about the configuration of the different relays here: [https://tasmota.github.io/docs/TuyaMCU/#switches](https://tasmota.github.io/docs/TuyaMCU/#switches)

**Comment by sillyfrog** [comment]
![IMG_0334](https://user-images.githubusercontent.com/816454/86416601-bfe67f00-bd0d-11ea-8228-8424ed232ad0.jpeg)
![IMG_0335](https://user-images.githubusercontent.com/816454/86417395-384e3f80-bd10-11ea-814b-7ab8054dc5c3.jpeg)

@dhilbig This is what my device looks like on the back and inside. I have used that template on a couple of devices so confident it works. Do you see any messages it the console when you have `weblog 4` on from the MCU?

**Comment by dhilbig** [comment]
I am not even able to get tasmota on it. Interesting that the circuit board is slightly different to the others I have and the one that you have shown. I am dealing with REV1.2-180919, so I am guessing they have changed their firmware as well to block OTA flashing.
![3 Gang Switch New Revision Crop](https://user-images.githubusercontent.com/67128598/86424846-f41a6980-bd26-11ea-9d89-22172d031760.jpg)

**Comment by sillyfrog** [comment]
@dhilbig Are you having issues with the latest Tuya-Convert? Obviously without Tasmota installed this step won’t be it much use.  Have you used Tuya-Convert before with success? I’m looking at getting more and hoping they have not changed so you can’t flash them :(

Worth checking https://github.com/ct-Open-Source/tuya-convert/issues/483 they may have recent firmware. Please let me know if you do have this version of firmware (looking at the logs), as that will affect some things for my own projects as well.

**Comment by dhilbig** [comment]
I have 5 of various gangs that I have had no problem with. This one I got last month and started to play with yesterday. Looks like it may be the newer firmware. Different ID'd and PSK's but getting the same decryption failed message as posted on the #483 issue.

**Comment by sillyfrog** [comment]
Thanks for the info, very good to know. That's a shame - I was looking to get a bunch of these for my own use (I was also playing with ones that were a bit older). May need to find another supplier or see if I can flash using serial (I saw they had headers, but never needed to even try them).

**Comment by networkdetective** [comment]
> @networkdetective I think it may come from the underlying `Base 54` template (I had a similar thought) - not 100% sure how these tie in together, but I found it's working with the latest Tasmota release (v8.3.1). Are you having issues?

I don't have any of these particular switches.  I only recently read all the Tasmota documentation about TuyaMCU and thought that you always needed the send/receive GPIO's.  There are apparently only 2 different configs, so perhaps Tasmota defaults to the one that works for you.

**Comment by fordarn** [comment]
Hi I have used the below GPIO template and run the command but home assistant is not discovering the turn on and turn off commands only all the energy information
{"NAME":"MakeGood 4 Gang","GPIO":[0,0,0,0,0,0,0,0,0,0,54,0,0],"FLAG":0,"BASE":54}
Backlog TuyaMCU 11,1; TuyaMCU 12,2; TuyaMCU 13,3; TuyaMCU 14,4; TuyaMCU 33,104; TuyaMCU 31,103; TuyaMCU 32,102;


Any ideas?

**Comment by andyidau** [comment]
These don't work with auto-dicovery. You need to manually configure. Here's my config for the first gang on the switch. Just replace POWER1 with 2, 3, 4 etc.

```
light:
  - platform: mqtt
    name: "Outdoor spa light"
    state_topic: "stat/kitchen_light_switch_a/RESULT"  
    value_template: "{{ value_json.POWER1 }}"
    command_topic: "cmnd/kitchen_light_switch_a/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "tele/kitchen_light_switch_a/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false
 ```

**Comment by fordarn** [comment]
Thanks worked a treat.
I have de Tuya-ed my house today 15 wall plates still going hopefull get it all finished tonight and back to normal.

**Comment by ryanbutterfield** [comment]
Hi all. Hopefully some extra information that may help someone.

I received a REV 2.01 board the other week direct from Makegood and was able to flash it directly, working around the MCU (Nuvoton N79E715AT28) issues and without soldering.

I used a continuity test to trace the VCC and GND of the TYWE3S chip to 2 pins on the 240v header (see attached picture). This allowed me to power it up easily using dupont connectors to the flasher (3.3v and GND).

I also traced the pad holes to the pin6 (RST) on the MCU, which needs to be grounded to stop the MCU from interfering from the flash, but I also found I required to GND pin7 also to make the flash work (this may not be required, but it made it work for me) (see attached picture).

With this, the standard 3 sec on RST + GPIO 0 and another 3 sec on GPIO 0, then holding TX/RX allowed me to run a backup/erase/flash successfully (see attached picture).

Update: This also worked with a REV 1.2 2-gang board.

![IMG_9581](https://user-images.githubusercontent.com/549478/88934846-6fd6ea00-d2c4-11ea-9d15-95e28648a02a.jpeg)
![IMG_9580x](https://user-images.githubusercontent.com/549478/88934870-78c7bb80-d2c4-11ea-9e7d-d5b835551c24.jpg)

**Comment by gohrobingo** [comment]
Hi,

I am total newbie to tuya convert (or smart home in general). I recently got a batch of makegood 1/2/3/4 switches but UK (86mm) version. Is the template still the same?

If they are the same, what do I put for 1 & 3 gangs as 2 & 4 gangs seems different.

Sorry if this question is too basic. But if anyone can guide me on the template and subsequently the console commands for all 4 gangs.

Thanks in advance!

P.S: If my light bulbs are tri-tone, any way to report the state (colour) currently set to? To change colour, i simply turn it off and on, the next colour appears.

**Comment by sillyfrog** [comment]
@gohrobingo If you have managed to flash Tasmota on to it already, then look at the [templates](https://templates.blakadder.com/index.html) for reference for the 2 & 4 gang (that's all I have, so all I could upload).

The 1 and 4 gangs will be very similar, I would suggest starting with the 4 gang template, and then figuring out which are actually needed. The [Tasmota docs](https://tasmota.github.io/docs/TuyaMCU/) cover the TuyaMCU. I have also [published a helper](https://github.com/sillyfrog/Tasmota-Tuya-Helper) to make it a lot easier to do the initial setup in the web GUI.

**Comment by gohrobingo** [comment]
Thanks @sillyfrog . Will take a look at the documents and the helper tool that you have written.

**Comment by pr0ssi** [comment]
> Hi all. Hopefully some extra information that may help someone.
> 
> I received a REV 2.01 board the other week direct from Makegood and was able to flash it directly, working around the MCU (Nuvoton N79E715AT28) issues and without soldering.
> 
> I used a continuity test to trace the VCC and GND of the TYWE3S chip to 2 pins on the 240v header (see attached picture). This allowed me to power it up easily using dupont connectors to the flasher (3.3v and GND).
> 
> I also traced the pad holes to the pin6 (RST) on the MCU, which needs to be grounded to stop the MCU from interfering from the flash, but I also found I required to GND pin7 also to make the flash work (this may not be required, but it made it work for me) (see attached picture).
> 
> With this, the standard 3 sec on RST + GPIO 0 and another 3 sec on GPIO 0, then holding TX/RX allowed me to run a backup/erase/flash successfully (see attached picture).
> 
> Update: This also worked with a REV 1.2 2-gang board.
> 
> ![IMG_9581](https://user-images.githubusercontent.com/549478/88934846-6fd6ea00-d2c4-11ea-9d15-95e28648a02a.jpeg)
> ![IMG_9580x](https://user-images.githubusercontent.com/549478/88934870-78c7bb80-d2c4-11ea-9e7d-d5b835551c24.jpg)

Thanks for this! I just received a large order of mixed pieces and a few were blocked from upgrading via tuya-convert. Following your steps I was able to reflash these

**Comment by z3r0ic** [comment]
Hi 

I have the 8 gang version MG-CM01W and flashed all ok with tasmota and ravencore, but cannot get it to boot up, no wifi showing etc, tried different flash modes but still nothing.... not sure whats up, also has a nuvoton MCU - NUC029LAN



https://www.nuvoton.com/resource-files/DS_NUC029_EN_Rev1.06.pdf



![1](https://user-images.githubusercontent.com/91279629/134550427-cd183f8c-4387-4fd3-95ae-66c6c9fc9331.jpg)
![2](https://user-images.githubusercontent.com/91279629/134550556-ff9adb6b-3971-45e2-8f59-32bdae7573c7.jpg)
![3](https://user-images.githubusercontent.com/91279629/134550568-8c92d778-e780-4a30-a1db-01162f15c216.jpg)

**Comment by sillyfrog** [comment]
@z3r0ic, how did you flash it? Was it via serial? If so, I would suggest looking at the Tx serial and see if you are getting any expected Tasmota output. I would imagine you need to pull the reset pins to the MCU's to prevent them causing issues. I think the first step is to see if the initial flash worked, and if Tasmota has any output, maybe showing any errors.

**Comment by z3r0ic** [comment]
@sillyfrog , sorry for late reply, got tasmota working all ok, but not haa ravencore
only problem is cannot find correct template, only have 6 relays working out the 8 from gui, they work fine physically... 

any suggestions pls?

thanks

**Comment by sillyfrog** [comment]
How did you get the existing relays working? If you used a template, then the only way (that I know) is via trial and error. If you already have some working, take note of these (turn them on and off in the UI, then you'll know which relays tie to which buttons). Then go to Configuration > Configure Template, and start setting some of the unused GIPO's (not the red ones) to relay, and use different ports. Eventually you'll find the ones that match. When that's all done, you should be able to figure out the correct order so they are labeled 1-8 in the UI matching the front of the face place. Good luck.

**Comment by sillyfrog** [comment]
How did you get the existing relays working? I'm assuming it's also an MCU, it which case check out my other project here: https://github.com/sillyfrog/Tasmota-Tuya-Helper

That'll help you identify the correct pins / ID's for Tasmota.

If you used a template, then the only way (that I know) is via trial and error. If you already have some working, take note of these (turn them on and off in the UI, then you'll know which relays tie to which buttons). Then go to Configuration > Configure Template, and start setting some of the unused GIPO's (not the red ones) to relay, and use different ports. Eventually you'll find the ones that match. When that's all done, you should be able to figure out the correct order so they are labeled 1-8 in the UI matching the front of the face place. Good luck.

**Comment by neo2angel** [comment]
If it helps anyone, all 8 switches work with the following template: 

Backlog TuyaMCU 11,1; TuyaMCU 12,2; TuyaMCU 13,3; TuyaMCU 14,4; TuyaMCU 15,5; TuyaMCU 16,6; TuyaMCU 17,101; TuyaMCU 18,102;
consumption and others I have not started to find out, if someone is encouraged... 


sorry my english... via google

**Comment by sillyfrog** [comment]
Thanks @neo2angel  - it would be great if you can post this to https://templates.blakadder.com/ to make it easier for others to find. See this for an example with TuyaMCU commands: https://templates.blakadder.com/makegood_MG-MD04W-2.html
